---
sudo: false
language: ruby
bundler_args: --without system_tests
script: "bundle exec rake validate lint spec"
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 4.0"
  - rvm: 2.3.1
    env: PUPPET_GEM_VERSION="~> 4.0"
notifications:
  email: false
